<?php

/**
 * @file
 * Contains view_display_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function view_display_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the view_display_field module.
    case 'help.page.view_display_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
